version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: owls-pick-postgres
    ports:
      - "5432:5432"
    environment:
      # ⚠️ application.yml에 적어둔 DB명, 유저, 비밀번호와 똑같이 맞춰주세요!
      POSTGRES_DB: owls_pick
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Dkdk9320"
    volumes:
      # 컨테이너를 삭제해도 데이터가 날아가지 않도록 볼륨 매핑
      - owls-pick-db-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:bookworm
    container_name: owls-pick-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  owls-pick-db-data: