services:
  owls-pick-api:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_REGION=ap-northeast-2
    # 컨테이너 메모리 초과로 인한 서버 멈춤 방지를 위한 최대 메모리 제한
    deploy:
      resources:
        limits:
          memory: 450M
    # Redis 캐시 서버가 완전히 구동된 이후에 API 서버를 실행하도록 순서 제어
    depends_on:
      redis:
        condition: service_started

  owls-pick-fastapi:
    environment:
      - APP_ENV=prod
    # 컨테이너 최대 메모리 제한
    deploy:
      resources:
        limits:
          memory: 250M

  prometheus:
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      # 컨테이너 재시작 시에도 수집된 메트릭 데이터를 보존하기 위한 볼륨 매핑
      - prometheus-data:/prometheus
    # 컨테이너 최대 메모리 제한
    deploy:
      resources:
        limits:
          memory: 80M

  grafana:
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # 대시보드 접근을 위한 관리자 계정 및 라우팅 경로 주입
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
    volumes:
      - grafana-data:/var/lib/grafana
    # 컨테이너 최대 메모리 제한
    deploy:
      resources:
        limits:
          memory: 200M

  loki:
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    # 컨테이너 최대 메모리 제한
    deploy:
      resources:
        limits:
          memory: 80M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 리버스 프록시 및 포워딩 규칙이 담긴 Nginx 메인 설정 파일 연결
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Certbot 도메인 인증 시 생성되는 임시 검증 파일을 Nginx가 서빙할 수 있도록 공유
      - ./certbot/www:/var/www/certbot
      # 발급이 완료된 Let's Encrypt SSL 인증서 키 파일들을 Nginx가 읽어오기 위한 경로 공유
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - owls-pick-api
      - grafana
    networks:
      - owls-pick-network
    restart: unless-stopped
    # 컨테이너 최대 메모리 제한
    deploy:
      resources:
        limits:
          memory: 80M

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
