x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m" # 로그 파일 하나당 최대 10MB
    max-file: "3"   # 최대 3개까지만 보관

services:
  owls-pick-api:
    image: seoleeder/owls-pick-spring-api:latest
    container_name: owls-pick-api
    networks:
      - owls-pick-network
    restart: unless-stopped
    logging: *default-logging

  owls-pick-fastapi:
    image: seoleeder/owls-pick-fastapi:latest
    container_name: owls-pick-fastapi
    networks:
      - owls-pick-network
    restart: unless-stopped
    logging: *default-logging

  redis:
    image: redis:bookworm
    container_name: owls-pick-redis
    command: redis-server --appendonly yes # AOF 방식을 켜서 디스크에 데이터 영구 저장
    environment:
      TZ: Asia/Seoul # KST 타임존 강제
    volumes:
      - owls-pick-redis-data:/data
    networks:
      - owls-pick-network # 전용 네트워크 지정
    restart: unless-stopped
    logging: *default-logging

  prometheus:
    image: prom/prometheus:latest
    container_name: owls-pick-prometheus
    networks:
      - owls-pick-network
    restart: unless-stopped
    logging: *default-logging

  grafana:
    image: grafana/grafana:latest
    container_name: owls-pick-grafana
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - prometheus
    networks:
      - owls-pick-network
    restart: unless-stopped
    logging: *default-logging

  loki:
    image: grafana/loki:2.9.8
    container_name: owls-pick-loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - owls-pick-network
    restart: unless-stopped
    logging: *default-logging

networks:
  owls-pick-network:
    driver: bridge

volumes:
  owls-pick-redis-data: