global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'owls-pick-spring-boot' # Spring Boot 수집 작업명
    metrics_path: '/actuator/prometheus'  # 메트릭 엔드포인트
    static_configs:
      - targets: ['owls-pick-api:8081']

  - job_name: 'owls-pick-fastapi' # FastAPI 수집 작업명
    metrics_path: '/metrics'  # 메트릭 엔드포인트
    static_configs:
      - targets: ['owls-pick-fastapi:8000']