events {
    # 워커 프로세스 1개당 동시에 처리할 수 있는 최대 연결 수 설정
    worker_connections 1024;
}

http {

    # OS 커널을 활용해 정적 파일을 빠르고 효율적으로 전송
    sendfile on;

    # 응답 헤더 내 Nginx 버전 정보 노출 차단
    server_tokens off;

    # 클라이언트 유휴 TCP 커넥션 유지 시간 설정 (65초)
    keepalive_timeout 65;

    # 정상 요청 처리 이력 저장 경로 지정
    access_log /var/log/nginx/access.log;

    # 예외 및 에러 발생 이력 저장 경로 및 로깅 레벨(warn) 지정
    error_log /var/log/nginx/error.log warn;

    # Spring Boot 라우팅 설정
    server {
        # 외부 HTTP 요청 수신 포트 바인딩
        listen 80;
        # 트래픽 수용 대상 도메인 식별자 지정
        server_name api.owls-pick.com;

        # Let's Encrypt 도메인 소유권 인증을 위한 전용 통로 개방
        location ^~ /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # 해당 도메인의 모든 경로(/)에 대한 처리 규칙
        location / {
            # 요청을 내부망의 Spring Boot 컨테이너 포트로 포워딩
            proxy_pass http://owls-pick-api:8080;

            # 백엔드로 전달할 원본 클라이언트 정보 프록시 헤더 주입
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 프록시 연결 및 응답 대기 제한 시간 설정
            proxy_read_timeout 60s;
            proxy_connect_timeout 60s;
        }
    }

    # Grafana (Monitoring) 라우팅 설정
    server {
        listen 80;
        server_name monitor.owls-pick.com;

        # [Let's Encrypt Webroot 인증용 경로]
        location ~/.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            # 요청을 내부망의 Grafana 컨테이너 포트로 포워딩
            proxy_pass http://owls-pick-grafana:3000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 웹소켓(WebSocket) 프로토콜 통신을 위한 연결 업그레이드 헤더 주입
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection upgrade;
        }
    }
}