create extension if not exists vector;

create table company
(
    id   bigint generated by default as identity
        primary key,
    logo varchar(255),
    name varchar(255) not null
        unique,
    url  text
);

create table game
(
    first_release      date,
    hypes              integer,
    created_at         timestamp(6),
    id                 bigint generated by default as identity  primary key,
    igdb_id            bigint
        unique,
    igdb_updated_at    timestamp(6),
    updated_at         timestamp(6),
    cover_id           varchar(30),
    rating_esrb        varchar(30),
    rating_kr          varchar(30),
    is_adult           BOOLEAN DEFAULT FALSE NOT NULL,
    type               varchar(30),
    description        varchar(255),
    itad_id            varchar(255) unique,
    release_status     varchar(255),
    storyline          varchar(255),
    title              varchar(255) not null,
    title_localization varchar(255),
    mode               text[],
    perspective        text[],
    platform           text[]
);

create table dashboard
(
    rank          integer,
    game_id       bigint       not null
        constraint fk_dashboard_game_id
            references game,
    id            bigint generated by default as identity
        primary key,
    reference_at  timestamp(6),
    updated_at    timestamp(6) not null,
    curation_type varchar(255) not null
        constraint dashboard_curation_type_check
            check ((curation_type)::text = ANY
        ((ARRAY ['WEEKLY_TOP_SELLER'::character varying, 'MONTHLY_TOP'::character varying, 'YEARLY_TOP'::character varying, 'CONCURRENT_PLAYER'::character varying, 'MOST_PLAYED'::character varying])::text[]))
    );

create table game_company
(
    is_developer boolean not null,
    is_publisher boolean not null,
    company_id   bigint  not null
        constraint fk_game_company_company_id
            references company,
    game_id      bigint  not null
        constraint fk_game_company_game_id
            references game,
    primary key (company_id, game_id)
);

create table language_support
(
    inter_support boolean,
    subtitle      boolean,
    voice_support boolean,
    game_id       bigint not null
        constraint fk_language_support_game_id
            references game,
    id            bigint generated by default as identity
        primary key,
    language      varchar(30)
);

create table playtime
(
    completionist integer,
    main_extras   integer,
    main_story    integer,
    game_id       bigint not null
        primary key
        constraint fk_playtime_game_id
            references game,
    updated_at    timestamp(6)
);

create table review
(
    playtime_at_review  integer,
    voted_up            boolean,
    votes_up            integer,
    weighted_vote_score numeric(5, 2),
    created_at          timestamp(6),
    game_id             bigint not null
        constraint fk_review_game_id
            references game,
    id                  bigint generated by default as identity
        primary key,
    recommendation_id   bigint not null,
    updated_at          timestamp(6),
    written_at          timestamp(6),
    review_text         text   not null
);

create table review_stat
(
    review_score      integer,
    total_negative    integer,
    total_positive    integer,
    total_review      integer,
    created_at        timestamp(6),
    game_id           bigint not null
        primary key
        constraint fk_review_stat_game_id
            references game,
    updated_at        timestamp(6),
    review_score_desc varchar(30),
    weekly_review integer not null default 0,
    review_summary TEXT
);

create table screenshot
(
    height   integer,
    width    integer,
    game_id  bigint       not null
        constraint fk_screenshot_game_id
            references game,
    id       bigint generated by default as identity
        primary key,
    image_id varchar(255) not null
);

create table store_detail
(
    discount_price integer,
    discount_rate  integer,
    historical_low integer,
    original_price integer,
    created_at     timestamp(6),
    expiry_date    timestamp(6),
    game_id        bigint      not null
        constraint fk_store_detail_game_id
            references game,
    id             bigint generated by default as identity
        primary key,
    updated_at     timestamp(6),
    store_name     varchar(20) not null
        constraint store_detail_store_name_check
            check ((store_name)::text = ANY
        ((ARRAY ['STEAM'::character varying, 'EPIC_GAMES_STORE'::character varying, 'UBISOFT_STORE'::character varying, 'EA_STORE'::character varying, 'MICROSOFT_STORE'::character varying, 'GREEN_MAN_GAMING'::character varying, 'GAMERSGATE'::character varying, 'FANATICAL'::character varying, 'BLIZZARD'::character varying])::text[])),
    store_app_id   varchar(255),
    url            text
);

create table tag
(
    game_id  bigint not null
        primary key
        constraint fk_tag_game_id
            references game,
    genres   text[],
    keywords text[],
    themes   text[]
);

create table users
(
    created_at          timestamp(6),
    id                  bigint generated by default as identity
        primary key,
    updated_at          timestamp(6),
    name                varchar(30)  not null,
    email               varchar(255) not null,
    nickname            varchar(30)  unique,
    birth_date          DATE,
    is_onboarded        BOOLEAN DEFAULT FALSE NOT NULL,
    is_discount_notification_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    preferred_stores    text[],
    preferred_tags      text[]
);

create table chat_session
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    updated_at timestamp(6),
    user_id    bigint not null
        constraint fk_chat_session_user_id
            references users,
    title      varchar(30)
);

create table chat_message
(
    created_at timestamp(6),
    id         bigint generated by default as identity
        primary key,
    session_id bigint       not null
        constraint fk_chat_message_session_id
            references chat_session,
    chat_role  varchar(255) not null
        constraint chat_message_chat_role_check
            check ((chat_role)::text = ANY ((ARRAY ['User'::character varying, 'CHATBOT'::character varying])::text[])),
    content    text
);

create table social_account
(
    user_id     bigint       not null
        primary key
        constraint fk_social_account_user_id
            references users,
    provider    varchar(30)  not null
        constraint social_account_provider_check
            check ((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'KAKAO'::character varying, 'NAVER'::character varying])::text[])),
    provider_id varchar(255) not null
);

create table wishlist
(
    created_at timestamp(6) not null,
    game_id    bigint       not null
        constraint fk_wishlist_game_id
            references game,
    user_id    bigint       not null
        constraint fk_wishlist_user_id
            references users,
    primary key (game_id, user_id)
);

create table fcm_token
(
    id         bigint generated by default as identity primary key,
    user_id    bigint       not null
        constraint fk_fcm_token_user_id
            references users,
    token      varchar(255) not null
        constraint uk_fcm_token unique,
    created_at timestamp(6),
    updated_at timestamp(6)
);

create table notification_history
(
    id                  bigint generated by default as identity primary key,
    user_id             bigint       not null
        constraint fk_notification_history_user_id
            references users,
    game_id             bigint       not null
        constraint fk_notification_history_game_id
            references game,
    title               varchar(255) not null,
    game_title          varchar(255) not null,
    discount_rate       integer      not null,
    expiry_date         timestamp(6) not null,
    is_read             boolean      not null default false,
    created_at          timestamp(6)
);


