-- AI 파이프라인 실패 작업 테이블 생성
create table genai_failed_task
(
    id            bigint generated by default as identity primary key,
    pipeline_type varchar(50)  not null,
    target_id     bigint       not null,
    trace_id      varchar(50),
    is_handled    boolean      not null default false,
    fail_reason   varchar(50),
    created_at    timestamp(6),
    updated_at    timestamp(6)
);

-- 무한 루프 방지 서브쿼리 및 스케줄러 폴링을 위한 복합 인덱스
create index if not exists idx_genai_failed_task_pipeline_handled on genai_failed_task (pipeline_type, is_handled);

-- Trace ID로 실패 내역을 역추적하기 위한 인덱스
create index if not exists idx_genai_failed_task_trace_id on genai_failed_task (trace_id);

-- 특정 엔티티가 실패 테이블에 존재하는지 빠른 조인을 위한 인덱스
create index if not exists idx_genai_failed_task_target_id on genai_failed_task (target_id);